services:
  my-spring-app-{COLOR}:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "{PORT}:8080"
    environment:
      - TZ=Asia/Seoul
    networks:
      - default_bridge

networks:
  default_bridge:
    external: true
    name: bridge