spring:
  config:
    import: application-secret.yml

  application:
    name: "agijagi"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      platform: dev

  jpa:
    show-sql: true
    open-in-view: false #default : true이기에 수정해야 함.
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  management:
    endpoints:
      web:
        exposure:
          include: health
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
